###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class ImageAnalysis(BaseModel):
    description: Optional["ImageCaption"] = None
    features: Optional["ImageFeatures"] = None
    objects: Optional[List["ImageObject"]] = None

class ImageCaption(BaseModel):
    caption: Optional[str] = None

class ImageFeatures(BaseModel):
    colors: List[str]
    sharpness: Optional[str] = None
    complexity: Optional[str] = None
    textures: List[str]

class ImageObject(BaseModel):
    name: Optional[str] = None
    colors: List[str]
    bounding_box: List[float]
